import { useEffect, useState } from 'react'
import { adminAPI, orgsAPI } from '../utils/http'
import { useApp } from '../context/AppContext'
import { PageShell, Spinner, SectionHeader } from './UI'
import { Matrix } from './Dashboard'

function Metric({label,value,detail,tone='purple'}){return <div className="admin-metric"><span>{label}</span><strong className={`metric-${tone}`}>{value}</strong>{detail&&<small>{detail}</small>}</div>}
function TrendBars({data=[]}){const max=Math.max(1,...data.map(d=>Number(d.checkins)||0));return <div className="trend-bars">{data.map((d,i)=><div className="trend-bar-col" key={`${d.date}-${i}`} title={`${d.date}: ${d.checkins} check-ins`}><div className="trend-bar" style={{height:`${Math.max(6,((Number(d.checkins)||0)/max)*100)}%`}}/><small>{new Date(d.date).toLocaleDateString('en-IN',{weekday:'short'}).slice(0,2)}</small></div>)}</div>}

export function AdminPage(){const{user,isSuperAdmin,isOrgAdmin}=useApp();if(!isSuperAdmin&&!isOrgAdmin)return <PageShell><div className="card" style={{textAlign:'center',padding:60}}><h2>Access Denied</h2></div></PageShell>;return isSuperAdmin?<SuperAdminDashboard/>:<OrgAdminDashboard orgId={user.org_id||user.orgId}/>}

function SupportCenter({orgId}){
 const[requests,setRequests]=useState([]);const[busy,setBusy]=useState(true);const[active,setActive]=useState(null);const[text,setText]=useState('');const[error,setError]=useState('')
 const load=()=>adminAPI.support(orgId).then(setRequests).catch(e=>setError(e.message||'Could not load support requests')).finally(()=>setBusy(false))
 useEffect(()=>{load()},[orgId])
 const send=async()=>{if(!active||!text.trim())return;setError('');try{await adminAPI.supportMessage(active.id,text.trim());setText('');await load()}catch(e){setError(e.message||'Could not send message')}}
 return <section className="card support-admin-card"><SectionHeader title="Support Center" subtitle="Pseudonymous communication. No individual wellness or distress scores are shown here."/>{busy?<Spinner green size={22}/>:!requests.length?<div className="insight-empty">No support requests at the moment.</div>:<div className="support-admin-grid"><div className="support-request-list">{requests.map(r=><button key={r.id} className={`support-request ${active?.id===r.id?'active':''}`} onClick={()=>setActive(r)}><div><strong>{r.member_code||'CNT-••••••••••'}</strong><small>{r.reason||'Support requested'} · {new Date(r.updated_at).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</small></div><span className="badge badge-blue">{r.status}</span></button>)}</div>{active&&<div className="support-conversation"><div className="support-conversation-head"><strong>{active.member_code}</strong><span>Support requested</span></div><p className="privacy-note">Identity is intentionally separated from wellness analytics.</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write a supportive message…" rows={5}/><button className="btn-primary" onClick={send}>Send supportive message</button></div>}</div>}{error&&<p className="support-feedback">{error}</p>}</section>
}

function SuperAdminDashboard(){const[stats,setStats]=useState(null);const[orgs,setOrgs]=useState([]);const[busy,setBusy]=useState(true);useEffect(()=>{Promise.all([adminAPI.stats(),orgsAPI.all()]).then(([s,o])=>{setStats(s);setOrgs(o||[])}).finally(()=>setBusy(false))},[]);if(busy||!stats)return <PageShell><Spinner green size={28}/></PageShell>;return <PageShell style={{maxWidth:1200}}><div className="admin-hero"><div><p className="eyebrow">PLATFORM CONTROL CENTER</p><h1>Superadmin Dashboard</h1><p>Monitor Countor platform health without exposing individual wellness data.</p></div><button className="btn-outline" onClick={()=>adminAPI.exportCSV()}>↓ Export report</button></div><div className="admin-metric-grid"><Metric label="Organizations" value={orgs.length||'—'} detail="active + pending"/><Metric label="Total users" value={stats.users.toLocaleString()} detail="registered members"/><Metric label="Active users" value={stats.activeUsers.toLocaleString()} detail="checked in last 30 days" tone="green"/><Metric label="Check-ins" value={stats.checkins.toLocaleString()} detail={`${stats.checkinRate}% active-user rate`}/><Metric label="Avg wellness" value={`${stats.avgWellbeing}%`} detail="platform average" tone="green"/><Metric label="Avg distress" value={`${stats.avgDistress}%`} detail="platform average" tone="amber"/></div><div className="admin-two-col"><section className="card"><SectionHeader title="Platform activity" subtitle="Check-ins over the last 7 days"/><TrendBars data={stats.daily7}/></section><section className="card"><SectionHeader title="Safety signals" subtitle="Aggregate monitoring only"/><div className="safety-summary"><strong>{stats.safetyAlerts}</strong><span>flagged check-ins today</span><small>Individual identities and raw responses are not displayed in admin analytics.</small></div></section></div><section className="card"><SectionHeader title="Organization overview" subtitle="Engagement and aggregate wellness signals across organizations"/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Organization</th><th>Members</th><th>Check-ins</th><th>Status</th></tr></thead><tbody>{orgs.slice(0,12).map(o=><tr key={o.id}><td><strong>{o.name}</strong></td><td>{o.member_count??0}</td><td>{o.checkin_count??0}</td><td><span className={`badge ${o.approved?'badge-green':'badge-amber'}`}>{o.approved?'Active':'Pending'}</span></td></tr>)}</tbody></table></div></section><SupportCenter/></PageShell>}

function OrgAdminDashboard({orgId}){const[stats,setStats]=useState(null);const[busy,setBusy]=useState(true);useEffect(()=>{adminAPI.stats(orgId).then(setStats).finally(()=>setBusy(false))},[orgId]);if(busy||!stats)return <PageShell><Spinner green size={28}/></PageShell>;const avgX=Math.round(stats.avgDistress||0),avgY=Math.round(stats.avgWellbeing||0),activeRate=stats.users?Math.round(stats.activeUsers/stats.users*100):0;return <PageShell style={{maxWidth:1200}}><div className="admin-hero"><div><p className="eyebrow">ORGANIZATION ANALYTICS</p><h1>Organization Dashboard</h1><p>Aggregate insights for your organization. Individual wellness scores remain private.</p></div><button className="btn-outline" onClick={()=>adminAPI.exportCSV(orgId)}>↓ Export report</button></div><div className="admin-metric-grid"><Metric label="Members" value={stats.users.toLocaleString()} detail="registered"/><Metric label="Active users" value={stats.activeUsers.toLocaleString()} detail="last 30 days" tone="green"/><Metric label="Check-in rate" value={`${activeRate}%`} detail="active members" tone="green"/><Metric label="Check-ins" value={stats.checkins.toLocaleString()} detail="all time"/><Metric label="Avg wellness" value={`${stats.avgWellbeing}%`} detail="aggregate only" tone="green"/><Metric label="Avg distress" value={`${stats.avgDistress}%`} detail="aggregate only" tone="amber"/></div><div className="admin-two-col"><section className="card"><SectionHeader title="Organization position" subtitle="Aggregate Wellness × Distress snapshot"/><div className="admin-matrix"><Matrix x={avgX} y={avgY} compact/></div><p className="privacy-note">This position represents the organization aggregate, not an individual employee.</p></section><section className="card"><SectionHeader title="Engagement" subtitle="Recent check-in activity"/><TrendBars data={stats.daily7}/><div className="admin-engagement"><div><strong>{stats.today}</strong><span>today</span></div><div><strong>{stats.activeUsers}</strong><span>active / 30d</span></div></div></section></div><section className="card"><SectionHeader title="Member engagement summary" subtitle="No employee names, emails, individual scores or individual risk labels are shown"/><div className="aggregate-callouts"><div><strong>{stats.activeUsers}</strong><span>members checked in within 30 days</span></div><div><strong>{Math.max(0,stats.users-stats.activeUsers)}</strong><span>members not active in 30 days</span></div><div><strong>{stats.safetyAlerts}</strong><span>aggregate safety signals today</span></div></div><div className="privacy-banner">🔒 <span>Countor keeps organization analytics aggregate-first. Use authorized support workflows for interventions requiring sensitive communication.</span></div></section><SupportCenter orgId={orgId}/></PageShell>}
